### ISSUE TITLE
Request to add an exchange

### ISSUE THREAD

**Issue by DINOSION** [brian-the-dev/tradingview-list#12]
Upbit.com is a representative exchange in Korea.
Most Koreans use upbit.com.
Could you please add an exchange?

**Comment by junlim0505** [comment]
add upbit please~~~ ^^

**Comment by brian-the-dev** [comment]
Hi @DINOSION,

Upbit is not available in TradingView (yet). As this database uses TradingView's API, I cannot add Upbit to the list. Try contacting TradingView's support and suggest them to add Upbit. Note that being listed on TradingView does not guarantee that the API is available for that exchange. Since this issue is beyond my control, I will close it and mark it as wontfix.

If you still have questions feel free to reply. Have a nice day!
