### ISSUE TITLE
futures screener missing from list.

### ISSUE THREAD

**Issue by cerebro1** [brian-the-dev/tradingview-list#13]
In symbol search, type HDFCBANK and select futures. It shows symbol HDFCBANK1!
Currently it is missing from your tradingview list.

**Comment by brian-the-dev** [comment]
Hello @cerebro1,

It's missing from the list because HDFCBANK1! does not have a Technicals tab (see [this issue](https://github.com/brian-the-dev/python-tradingview-ta/issues/28#issuecomment-864880271)). The scanner API is only accessible when Technicals are available. Unfortunately, this has nothing to do with my project but is a limitation from tradingview itself. However, you can still use the non-futures HDFCBANK.

I'm going to close this issue as it is currently unfixable. If you still have questions don't hesitate to reply. Have a good one.
