### ISSUE TITLE
Gate.io?

### ISSUE THREAD

**Issue by ryanza** [brian-the-dev/tradingview-list#17]
GATEIO missing from list but available on tradingview? Any help here?

**Comment by brian-the-dev** [comment]
Only assets with technical analysis available are listed in the database. Technical analysis is not available on every exchange. Try comparing [this page](https://www.tradingview.com/symbols/BTCUSDT/technicals/) with [this page](https://www.tradingview.com/symbols/BTCUSDT/?exchange=GATEIO), there is no technicals tab. There will be no gate.io in the list because it does not exist in https://scanner.tradingview.com/crypto/scan.

If you're using tradingview-ta to retrieve technical analysis from TradingView, I suggest you use a different exchange as the indicators are not much of a difference.

![image](https://user-images.githubusercontent.com/40331046/161876862-5725ed50-ed68-41ee-b598-f30ee43cb58b.png)
![image](https://user-images.githubusercontent.com/40331046/161876881-daa8ebbf-e146-4dd9-b2d4-7459926dadda.png)


I hope this answers your question. If you have further questions please reply to my comment. Have a good one!
