### ISSUE TITLE
Show all symbols instead of 20 (pagination)

### ISSUE THREAD

**Issue by saud133** [brian-the-dev/tradingview-list#32]
Hello
if you please till me how i can see or load all symbol of ksa (saudi stock)
i see note in the site (Results are limited to 20 to reduce server load.)

**Comment by brian-the-dev** [comment]
Hi @saud133,

Sorry for the inconvenience. Since pagination isn't available yet, you won't be able to see all of the symbols at once. You can open [this link](https://scanner.tradingview.com/ksa/scan) to see all the symbols, but there'll be no description. Please keep this issue open, and I'll close it once I have the time to implement it.

**Comment by saud133** [comment]
thanks alot

**Comment by brian-the-dev** [comment]
Pagination is now supported, now you can view more than 20 results. I'm closing this issue now, thanks for the feedback.
