### ISSUE TITLE
could you add more forex pair?

### ISSUE THREAD

**Issue by tsenchialee** [brian-the-dev/tradingview-list#35]
such as XAU/USD,XAG/USD in FXCM

**Comment by brian-the-dev** [comment]
Unfortunately, those pairs are unavailable due to a limitation on TradingView's API. I have no control over this and there's no workaround yet. In order for the tradingview-ta library to retrieve information about a pair, it needs to have the technicals tab on TradingView's website:

Compare XAUUSD:
![image](https://user-images.githubusercontent.com/40331046/177909130-ee640f93-34b2-4a02-bea1-d52a01bc0b83.png)

to other pairs:
![image](https://user-images.githubusercontent.com/40331046/177909295-32ef412f-7cef-495f-9610-14ddc06d7da6.png)

P.S. XAU/USD and XAG/USD are categorized by TradingView as CFD, not forex.
